default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: kindle_highlight_development

test:
  <<: *default
  database: kindle_highlight_test

production:
  <<: *default
  database: kindle_highlight_production
